version: '3'
services:
  westworldbot1:
    image: tvshow.azurecr.io/tvbot1:v1
    # build: .
    environment:
      - ACCESS_TOKEN=5398859275:AAH5X0dOUBOspdDvhcVUYoM93TRJu-e8m2g
      - KEY_PATH=secret_key.json
      - DATABASE_URL=https://comp7940projectmt-default-rtdb.asia-southeast1.firebasedatabase.app/
    command: python main.py

  westworldbot2:
    image: tvshow.azurecr.io/tvbot:v1
    # build: .
    environment:
      - ACCESS_TOKEN=5160604243:AAE6Qs-_21_3325ONlKIpO-gybcsYQzaqlA
      - KEY_PATH=secret_key.json
      - DATABASE_URL=https://comp7940projectmt-default-rtdb.asia-southeast1.firebasedatabase.app/
    command: python main.py

